include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # freezed v3 known issue - JsonKey on constructor params
    invalid_annotation_target: ignore

linter:
  rules:
    # DNS fields (TC, RD, RA, AD, CD, TTL) follow RFC standard naming
    non_constant_identifier_names: false
